import { MCP_READ_SCOPE, OpaqueIdSchema, EndpointBundleSchema, type EndpointBundle } from "@vault-mcp-bridge/contracts";
import { randomBytes } from "node:crypto";
import { hashOpaque, iso } from "./crypto.js";
import type { OAuthService } from "./oauth.js";
import type { CredentialVault, ProvisionedTunnel, TunnelProvider } from "./providers.js";
import { CredentialLeaseError, createCredentialLease, materializeCredential, type CredentialLeaseResponse, type MaterializedCredential } from "./lease.js";
import { DEFAULT_EDGE_LIMITS, resolveLimits, type EdgeLimits } from "./limits.js";
import { pruneStore } from "./store.js";
import type { CredentialKind, EdgeClock, EdgeStore, EdgeMode, InstallationRecord } from "./types.js";

export type EdgeServiceOptions = {
  mode: EdgeMode;
  origin: string;
  issuer: string;
  provider: TunnelProvider;
  store: EdgeStore;
  oauth: OAuthService;
  credentialVault?: CredentialVault;
  limits?: Partial<EdgeLimits>;
  now?: EdgeClock;
};

const makeInstallationId = (): string => `inst_${randomBytes(18).toString("hex")}`;

export class EdgeCapacityError extends Error {
  constructor() {
    super("edge capacity is temporarily unavailable");
    this.name = "EdgeCapacityError";
  }
}

export class IdempotencyKeyError extends Error {
  constructor(readonly conflict = false) {
    super(conflict ? "idempotency key conflict" : "idempotency key is invalid");
    this.name = "IdempotencyKeyError";
  }
}

export class InstallationNotFoundError extends Error {
  constructor() {
    super("installation not found");
    this.name = "InstallationNotFoundError";
  }
}

const IDEMPOTENCY_KEY_RE = /^[A-Za-z0-9._~:-]{16,128}$/u;

export type InstallationProvisionRequest = {
  vaultId: string;
  /** One canonical identifier is generated by the desktop orchestrator and
   * reused by edge, Compose labels and JWT claims. */
  installationId?: string;
  /** Public certificate request only; never a TLS private key. */
  publisherCsr?: string;
};

export type InstallationCreateResult = { record: InstallationRecord; idempotent: boolean };

export class EdgeService {
  readonly mode: EdgeMode;
  readonly origin: URL;
  readonly issuer: string;
  readonly oauth: OAuthService;
  private readonly provider: TunnelProvider;
  private readonly store: EdgeStore;
  private readonly now: EdgeClock;
  private readonly credentialVault: CredentialVault | undefined;
  private readonly limits: EdgeLimits;
  private readonly provisioning = new Map<string, Promise<InstallationCreateResult>>();

  constructor(options: EdgeServiceOptions) {
    this.mode = options.mode;
    this.origin = new URL(options.origin);
    this.issuer = options.issuer;
    this.provider = options.provider;
    this.store = options.store;
    this.oauth = options.oauth;
    this.credentialVault = options.credentialVault;
    this.limits = resolveLimits(options.limits ?? DEFAULT_EDGE_LIMITS);
    this.now = options.now ?? Date.now;
  }

  async createInstallation(ownerId: string, vaultId: string, idempotencyKey?: string): Promise<InstallationRecord> {
    return (await this.createInstallationResult(ownerId, { vaultId }, idempotencyKey)).record;
  }

  async createInstallationResult(ownerId: string, request: string | InstallationProvisionRequest, idempotencyKey?: string): Promise<InstallationCreateResult> {
    const input = typeof request === "string" ? { vaultId: request } : request;
    const operationKey = idempotencyKey ? `${ownerId}:${hashOpaque(idempotencyKey)}` : undefined;
    if (operationKey) {
      const active = this.provisioning.get(operationKey);
      if (active) return active;
      const operation = this.createInstallationOnce(ownerId, input, idempotencyKey).finally(() => {
        this.provisioning.delete(operationKey);
      });
      this.provisioning.set(operationKey, operation);
      return operation;
    }
    return this.createInstallationOnce(ownerId, input, idempotencyKey);
  }

  private async createInstallationOnce(ownerId: string, input: InstallationProvisionRequest, idempotencyKey?: string): Promise<InstallationCreateResult> {
    if (!ownerId || ownerId.length > 256) throw new Error("owner id is invalid");
    const vaultId = input.vaultId;
    OpaqueIdSchema.parse(vaultId);
    if (input.installationId !== undefined) OpaqueIdSchema.parse(input.installationId);
    if (input.publisherCsr !== undefined && (input.publisherCsr.length < 128 || input.publisherCsr.length > 16 * 1024 || !/^-----BEGIN CERTIFICATE REQUEST-----[\s\S]+-----END CERTIFICATE REQUEST-----\s*$/u.test(input.publisherCsr))) {
      throw new Error("publisher CSR is invalid");
    }
    if (idempotencyKey !== undefined && !IDEMPOTENCY_KEY_RE.test(idempotencyKey)) throw new IdempotencyKeyError();
    pruneStore(this.store, this.now());
    if (idempotencyKey) {
      const keyHash = hashOpaque(idempotencyKey);
      const previous = this.store.installationIdempotency.get(keyHash);
      if (previous) {
        if (previous.ownerId !== ownerId || previous.vaultId !== vaultId || (input.installationId !== undefined && previous.installationId !== input.installationId)) throw new IdempotencyKeyError(true);
        const existing = this.store.installations.get(previous.installationId);
        if (existing) return { record: existing, idempotent: true };
        this.store.installationIdempotency.delete(keyHash);
      }
      this.pruneIdempotencyKeys();
      if (this.store.installationIdempotency.size >= this.limits.maxIdempotencyKeys) throw new EdgeCapacityError();
    }
    this.pruneRevokedInstallations();
    const active = [...this.store.installations.values()].filter((record) => record.status !== "revoked");
    const ownerActive = active.filter((record) => record.ownerId === ownerId);
    if (active.length >= this.limits.maxInstallations || ownerActive.length >= this.limits.maxInstallationsPerOwner) throw new EdgeCapacityError();
    const installationId = input.installationId ?? makeInstallationId();
    const sameId = this.store.installations.get(installationId);
    if (sameId) {
      if (sameId.ownerId === ownerId && sameId.vaultId === vaultId && sameId.status !== "revoked") {
        if (idempotencyKey) this.store.installationIdempotency.set(hashOpaque(idempotencyKey), { keyHash: hashOpaque(idempotencyKey), ownerId, vaultId, installationId, createdAt: this.now() });
        await this.flushStore();
        return { record: sameId, idempotent: true };
      }
      throw new IdempotencyKeyError(true);
    }
    const provisioned = await this.provider.provision({ installationId, vaultId, ownerId, ...(input.publisherCsr ? { publisherCsr: input.publisherCsr } : {}) });
    const now = this.now();
    const endpointBundle = this.buildBundle(installationId, vaultId, provisioned, now);
    const record: InstallationRecord = {
      installationId,
      ownerId,
      vaultId,
      mode: this.mode,
      status: "ready",
      providerResourceId: provisioned.providerResourceId,
      endpointBundle,
      createdAt: iso(now),
      updatedAt: iso(now),
    };
    this.store.installations.set(installationId, record);
    if (idempotencyKey) {
      this.store.installationIdempotency.set(hashOpaque(idempotencyKey), { keyHash: hashOpaque(idempotencyKey), ownerId, vaultId, installationId, createdAt: now });
    }
    await this.flushStore();
    return { record, idempotent: false };
  }

  getInstallation(installationId: string): InstallationRecord | null {
    return this.store.installations.get(installationId) ?? null;
  }

  listInstallations(ownerId: string): InstallationRecord[] {
    return [...this.store.installations.values()].filter((record) => record.ownerId === ownerId);
  }

  async rotateInstallation(ownerId: string, installationId: string): Promise<InstallationRecord> {
    const record = this.requireOwnerInstallation(ownerId, installationId);
    if (record.status === "revoked") throw new Error("installation is revoked");
    const previous = this.toProvisioned(record);
    const next = await this.provider.rotate({ installationId, vaultId: record.vaultId, ownerId }, previous);
    const now = this.now();
    record.endpointBundle = this.buildBundle(installationId, record.vaultId, next, now);
    record.providerResourceId = next.providerResourceId;
    record.updatedAt = iso(now);
    await this.flushStore();
    return record;
  }

  async revokeInstallation(ownerId: string, installationId: string): Promise<void> {
    const record = this.requireOwnerInstallation(ownerId, installationId);
    if (record.status === "revoked") return;
    await this.provider.revoke({ installationId, vaultId: record.vaultId, ownerId }, this.toProvisioned(record));
    const now = this.now();
    record.status = "revoked";
    record.revokedAt = iso(now);
    record.updatedAt = iso(now);
    for (const [clientId, client] of this.store.clients) {
      if (client.installationId === installationId) this.store.clients.delete(clientId);
    }
    for (const [codeHash, code] of this.store.authorizationCodes) {
      if (code.installationId === installationId) this.store.authorizationCodes.delete(codeHash);
    }
    for (const [tokenHash, token] of this.store.refreshTokens) {
      if (token.installationId === installationId) this.store.refreshTokens.delete(tokenHash);
    }
    for (const [leaseId, lease] of this.store.credentialLeases) {
      if (lease.installationId === installationId) this.store.credentialLeases.delete(leaseId);
    }
    await this.flushStore();
  }

  /** Revoke one OAuth client without deleting its DCR registration. Access
   * tokens become inactive via the client's epoch; codes and refresh tokens
   * are removed as part of the same single-writer mutation. */
  async revokeClient(ownerId: string, installationId: string, clientId: string): Promise<boolean> {
    const record = this.requireOwnerInstallation(ownerId, installationId);
    if (record.status === "revoked") return false;
    const client = this.store.clients.get(clientId);
    if (!client || client.installationId !== installationId) return false;
    return this.oauth.revokeClient(installationId, clientId);
  }

  createCredentialLease(ownerId: string, installationId: string, kind: CredentialKind, clientPublicKey: string): CredentialLeaseResponse {
    const record = this.requireOwnerInstallation(ownerId, installationId);
    if (record.status === "revoked") throw new CredentialLeaseError("not_found", "installation not found");
    if (!this.credentialVault) throw new CredentialLeaseError("secret_unavailable", "credential store is unavailable");
    return createCredentialLease(this.store, ownerId, installationId, kind, clientPublicKey, this.now, undefined, this.limits);
  }

  async redeemCredentialLease(ownerId: string, leaseId: string): Promise<MaterializedCredential> {
    const lease = this.store.credentialLeases.get(leaseId);
    if (!lease || lease.ownerId !== ownerId) throw new CredentialLeaseError("not_found", "credential lease not found");
    if (lease.expiresAt <= this.now()) {
      this.store.credentialLeases.delete(leaseId);
      throw new CredentialLeaseError("expired", "credential lease expired");
    }
    const record = this.store.installations.get(lease.installationId);
    if (!record || record.status === "revoked") throw new CredentialLeaseError("not_found", "installation not found");
    if (!this.credentialVault) throw new CredentialLeaseError("secret_unavailable", "credential store is unavailable");
    const reference = lease.kind === "tunnel"
      ? record.endpointBundle.tunnelCredential
      : lease.kind === "publisher-mtls"
        ? record.endpointBundle.publisherMtlsCredential
        : lease.kind === "publisher-edge-attestation"
          ? record.endpointBundle.publisherEdgeAttestation
          : record.endpointBundle.mcpEdgeAttestation;
    if (!reference) throw new CredentialLeaseError("secret_unavailable", "credential store is unavailable");
    const secret = await this.credentialVault.get(reference);
    return materializeCredential(this.store, ownerId, leaseId, secret, this.now);
  }

  requireOwnerInstallation(ownerId: string, installationId: string): InstallationRecord {
    const record = this.store.installations.get(installationId);
    if (!record || record.ownerId !== ownerId) throw new InstallationNotFoundError();
    return record;
  }

  resolveByHost(host: string): InstallationRecord | null {
    const normalized = host.toLowerCase().replace(/:\d+$/u, "");
    for (const record of this.store.installations.values()) {
      if (record.endpointBundle.mcpHost === normalized || record.endpointBundle.publisherHost === normalized) return record;
    }
    return null;
  }

  protectedResourceMetadata(record: InstallationRecord): Record<string, unknown> {
    return {
      resource: record.endpointBundle.mcpResourceUrl,
      authorization_servers: [this.issuer],
      scopes_supported: [MCP_READ_SCOPE],
      bearer_methods_supported: ["header"],
    };
  }

  /** Resolve a resource indicator without exposing installation ownership. */
  findByResource(resource: string): InstallationRecord | null {
    for (const record of this.store.installations.values()) {
      if (record.endpointBundle.mcpResourceUrl === resource) return record;
    }
    return null;
  }

  private buildBundle(installationId: string, vaultId: string, provisioned: ProvisionedTunnel, now: number): EndpointBundle {
    const mcpResourceUrl = provisioned.mcpResourceUrl;
    const bundle: EndpointBundle = {
      version: 1,
      installationId,
      vaultId,
      mcpResourceUrl,
      publisherUrl: provisioned.publisherUrl,
      mcpHost: provisioned.mcpHost,
      publisherHost: provisioned.publisherHost,
      oauthIssuer: this.issuer,
      oauthAuthorizationEndpoint: `${this.issuer}/oauth/authorize`,
      oauthTokenEndpoint: `${this.issuer}/oauth/token`,
      oauthJwksUri: `${this.issuer}/.well-known/jwks.json`,
      // Protected-resource metadata belongs to the MCP resource origin. The
      // authorization server cannot infer an installation from its own host.
      oauthProtectedResourceMetadataUrl: new URL("/.well-known/oauth-protected-resource/mcp", mcpResourceUrl).toString(),
      oauthAudience: mcpResourceUrl,
      tunnelCredential: provisioned.tunnelCredential,
      publisherMtlsCredential: provisioned.publisherMtlsCredential,
      publisherEdgeAttestation: provisioned.publisherEdgeAttestation,
      mcpEdgeAttestation: provisioned.mcpEdgeAttestation,
      oauthVerificationBundle: this.oauth.verificationBundle(mcpResourceUrl, now),
    };
    return EndpointBundleSchema.parse(bundle);
  }

  private toProvisioned(record: InstallationRecord): ProvisionedTunnel {
    return {
      providerResourceId: record.providerResourceId,
      mcpResourceUrl: record.endpointBundle.mcpResourceUrl,
      publisherUrl: record.endpointBundle.publisherUrl,
      mcpHost: record.endpointBundle.mcpHost,
      publisherHost: record.endpointBundle.publisherHost,
      tunnelCredential: record.endpointBundle.tunnelCredential,
      publisherMtlsCredential: record.endpointBundle.publisherMtlsCredential,
      publisherEdgeAttestation: record.endpointBundle.publisherEdgeAttestation,
      mcpEdgeAttestation: record.endpointBundle.mcpEdgeAttestation,
    };
  }

  private pruneRevokedInstallations(): void {
    if (this.store.installations.size < this.limits.maxInstallations) return;
    const revoked = [...this.store.installations.values()]
      .filter((record) => record.status === "revoked")
      .sort((left, right) => Date.parse(left.revokedAt ?? left.updatedAt) - Date.parse(right.revokedAt ?? right.updatedAt));
    for (const record of revoked) {
      if (this.store.installations.size < this.limits.maxInstallations) break;
      this.store.installations.delete(record.installationId);
      for (const [keyHash, entry] of this.store.installationIdempotency) if (entry.installationId === record.installationId) this.store.installationIdempotency.delete(keyHash);
    }
  }

  private pruneIdempotencyKeys(): void {
    if (this.store.installationIdempotency.size < this.limits.maxIdempotencyKeys) return;
    const stale = [...this.store.installationIdempotency.values()]
      .filter((entry) => !this.store.installations.has(entry.installationId))
      .sort((left, right) => left.createdAt - right.createdAt);
    for (const entry of stale) {
      if (this.store.installationIdempotency.size < this.limits.maxIdempotencyKeys) break;
      this.store.installationIdempotency.delete(entry.keyHash);
    }
  }

  private async flushStore(): Promise<void> {
    const candidate = this.store as EdgeStore & { flush?: () => Promise<void> };
    if (candidate.flush) await candidate.flush();
  }
}
